language: node_js
node_js:
    - 11.6.0
cache: yarn

install:
    - yarn install

script:
    - yarn test

addons:
  apt:
    packages:
    - sshpass

#deploy:
    # provider: pages
    #skip-cleanup: true
    #github-token: $GITHUB_TOKEN
    # local_dir: build
    #on:
        #branch: master
        
after_success:
    - export SSHPASS=$DEPLOY_PASS
    #- sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    #- sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh
    - sshpass -e ssh localadmin@103.106.81.48 /home/localadmin/jest-learn/deploy.sh